name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on: [push, pull_request]


jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 1: Build project
    - name: Gradle build
      run: ./gradlew build

    # Step 2: Check the code with ktlint, you can remove this job if you don't use ktlint
    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck

